### ISSUE TITLE
Preoomkiller ignores/not-forwarding STOPSIGNAL signals to child process

### ISSUE THREAD

**Issue by rchenzheng** [grosser/preoomkiller#7]
We've been using preoomkiller to prevent OOM termination from kubernetes, but it seems that when the `STOPSIGNAL` that's sent by kubernetes is not getting forwarded or received the the process that's wrapping. So it continues to work until the grace period runs out and it is eventually forcibly terminated.

Steps to reproduce:

- Wrap a process 
  - `./preoomkiller -p 80 hello-world run`
- Send `STOPSIGNAL` from kubernetes
  - `kubectl delete pod $POD`
- Notice how it will not terminate immediately

**Comment by grosser** [comment]
yeah, it needs to capture all (or maybe just this) signal and forward it to the process
PR welcome
